### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by Filimoa** [Filimoa/open-parse#1]
## Description
This is a tentative roadmap, I will update it as things evolve.

## Roadmap
- [ ] Speed up parsing. Due to the way we construct TextSpan this can be quite slow especially on documents with tons of tables
- [ ] Improve table-transformers performance. There might be ways to preprocess the images to help with detection
- [ ] Implement other table models
- [ ] Implement PostProcessing functions. Tons of promising avenues here.
- [ ] Add `embed_text` property, useful on tables where embedding the contents performs poorly
- [ ] Add support for ImageElements

**Comment by shekhars-li** [comment]
Hey @Filimoa do you plan to add support for unitable anytime soon? Seems like the doc mentions it but the notebook does not have an example for it. Thanks for creating this project.

**Comment by Filimoa** [comment]
> Hey @Filimoa do you plan to add support for unitable anytime soon? Seems like the doc mentions it but the notebook does not have an example for it. Thanks for creating this project.

As soon as the pre-trained weights are released I'll be adding it. I talked with the ShengYun earlier this week and sounds like they'll be released ASAP.

**Comment by shekhars-li** [comment]
@Filimoa Looks like pretrained weights are available now! :)

**Comment by Filimoa** [comment]
In progress! Should be merged in by the end of the week.

**Comment by Filimoa** [comment]
Just merged try it out, it will require downloading weights which you can read about [here](https://filimoa.github.io/open-parse/parsing-tables/unitable/).

**Comment by Ulipenitz** [comment]
Hey @Filimoa! Really great project!! 
Have you thought about using open source models for the semantic processing?
You can find even better embedding models here: https://huggingface.co/spaces/mteb/leaderboard
Especially this one is really promising (only 0.67GB & better than text-embedding-3-large): https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1
There are also ONNX models, running pretty fast on CPUs.

**Comment by Filimoa** [comment]
Added to the roadmap! Will ship very soon @Ulipenitz

**Comment by cthompson-insight** [comment]
Would be great to support Azure OpenAI as well.

**Comment by ZinoKader** [comment]
> Would be great to support Azure OpenAI as well.

```
from langchain_openai.embeddings import AzureOpenAIEmbeddings
import os

os.environ['AZURE_OPENAI_ENDPOINT'] = "https://..."
os.environ['AZURE_OPENAI_API_KEY'] = "..."

chunker = SemanticChunker(AzureOpenAIEmbeddings(), ...)
```

**Comment by zishengwu** [comment]
Hey @Filimoa ! Have you try [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) ? As for me, this project have well performance for Layout Analysis and Table Recognition

**Comment by faileon** [comment]
hello, i was playing with this library for the very first time today. it is very good, but i am missing image extraction. usually i need to work with images in some maner, for example sending them to a multimodal llm for description or similar. but for the PDFs I tried I am not getting any images back - is that what the ` Add support for ImageElements` will bring? thanks

**Comment by borisevstratov** [comment]
First of all, huge thanks for the project - amazing work!

> Create a docker image with fastapi for non python users

I built a Dockerized FastAPI wrapper that does exactly that: https://github.com/borisevstratov/open-parse-api
Already using it in production. Feel free to fork/copy!
